### ISSUE TITLE
Hi, the bridge script always goes to failed with cancled. do you help any idea about it?

### ISSUE THREAD

**Issue by AflenChen** [viter0layer/zkSync-Era-bridger-to-L1#1]
Here is the screenshot:

![zksync issue](https://github.com/viter0layer/zkSync-Era-bridger-to-L1/assets/10666896/1fb5b733-939f-43dc-95d6-ce052846fdfa)

https://era.zksync.network/tx/0x68383116de7e986638c177cd80ac1a53bb57163243e8b83d2f854f5fc730478a

**Comment by viter0layer** [comment]
Just increese Gas Limit: 2-3m gas limit should be enough
